// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/proto/consignment/consignment.proto

/*
Package go_micro_srv_consignment is a generated protocol buffer package.

It is generated from these files:
	service/proto/consignment/consignment.proto

It has these top-level messages:
	Consignment
	Container
	Response
*/
package go_micro_srv_consignment

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Consignment struct {
	Id          string       `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Description string       `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Weight      int32        `protobuf:"varint,3,opt,name=weight" json:"weight,omitempty"`
	Containers  []*Container `protobuf:"bytes,4,rep,name=containers" json:"containers,omitempty"`
	Vessel      string       `protobuf:"bytes,5,opt,name=vessel" json:"vessel,omitempty"`
}

func (m *Consignment) Reset()                    { *m = Consignment{} }
func (m *Consignment) String() string            { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()               {}
func (*Consignment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Consignment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Consignment) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Consignment) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Consignment) GetVessel() string {
	if m != nil {
		return m.Vessel
	}
	return ""
}

type Container struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Customer string `protobuf:"bytes,2,opt,name=customer" json:"customer,omitempty"`
	Origin   string `protobuf:"bytes,3,opt,name=origin" json:"origin,omitempty"`
	User     string `protobuf:"bytes,4,opt,name=user" json:"user,omitempty"`
}

func (m *Container) Reset()                    { *m = Container{} }
func (m *Container) String() string            { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()               {}
func (*Container) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetCustomer() string {
	if m != nil {
		return m.Customer
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Container) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type Response struct {
	Created     bool         `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
	Consignment *Consignment `protobuf:"bytes,2,opt,name=consignment" json:"consignment,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

func init() {
	proto.RegisterType((*Consignment)(nil), "go.micro.srv.consignment.Consignment")
	proto.RegisterType((*Container)(nil), "go.micro.srv.consignment.Container")
	proto.RegisterType((*Response)(nil), "go.micro.srv.consignment.Response")
}

func init() { proto.RegisterFile("service/proto/consignment/consignment.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcb, 0x6a, 0xeb, 0x30,
	0x10, 0x86, 0x71, 0x6e, 0x27, 0x1e, 0xc3, 0x29, 0xd5, 0xa2, 0x88, 0xac, 0x8c, 0x4b, 0xc1, 0x50,
	0x50, 0xc0, 0x7d, 0x04, 0x2f, 0xba, 0x57, 0xf6, 0x85, 0x54, 0x1e, 0x9c, 0x81, 0x5a, 0x72, 0x25,
	0xc5, 0x7d, 0xb1, 0x3e, 0x60, 0x89, 0x62, 0xa7, 0x82, 0x92, 0xd2, 0xdd, 0x7c, 0x9a, 0xcb, 0xff,
	0x0f, 0x23, 0x78, 0x74, 0x68, 0x07, 0x52, 0xb8, 0xed, 0xad, 0xf1, 0x66, 0xab, 0x8c, 0x76, 0xd4,
	0xea, 0x0e, 0xb5, 0x8f, 0x63, 0x11, 0xb2, 0x8c, 0xb7, 0x46, 0x74, 0xa4, 0xac, 0x11, 0xce, 0x0e,
	0x22, 0xca, 0x17, 0x9f, 0x09, 0x64, 0xf5, 0x37, 0xb3, 0xff, 0x30, 0xa3, 0x86, 0x27, 0x79, 0x52,
	0xa6, 0x72, 0x46, 0x0d, 0xcb, 0x21, 0x6b, 0xd0, 0x29, 0x4b, 0xbd, 0x27, 0xa3, 0xf9, 0x2c, 0x24,
	0xe2, 0x27, 0x76, 0x07, 0xab, 0x0f, 0xa4, 0xf6, 0xe0, 0xf9, 0x3c, 0x4f, 0xca, 0xa5, 0x1c, 0x89,
	0xd5, 0x00, 0xca, 0x68, 0xbf, 0x27, 0x8d, 0xd6, 0xf1, 0x45, 0x3e, 0x2f, 0xb3, 0xea, 0x5e, 0x5c,
	0x33, 0x22, 0xea, 0xa9, 0x56, 0x46, 0x6d, 0xa7, 0xe1, 0x03, 0x3a, 0x87, 0x6f, 0x7c, 0x19, 0x94,
	0x47, 0x2a, 0x14, 0xa4, 0x97, 0x86, 0x1f, 0x9e, 0x37, 0xb0, 0x56, 0x47, 0xe7, 0x4d, 0x87, 0x76,
	0x34, 0x7c, 0xe1, 0xd3, 0x40, 0x63, 0xa9, 0x25, 0x1d, 0xdc, 0xa6, 0x72, 0x24, 0xc6, 0x60, 0x71,
	0x74, 0x68, 0xf9, 0x22, 0xbc, 0x86, 0xb8, 0xe8, 0x60, 0x2d, 0xd1, 0xf5, 0x46, 0x3b, 0x64, 0x1c,
	0xfe, 0x29, 0x8b, 0x7b, 0x8f, 0x67, 0xa1, 0xb5, 0x9c, 0x90, 0x3d, 0x43, 0x16, 0xed, 0x11, 0x04,
	0xb3, 0xea, 0xe1, 0xd7, 0x45, 0xa7, 0x58, 0xc6, 0x9d, 0xd5, 0x3b, 0xdc, 0xec, 0x0e, 0xd4, 0xf7,
	0xa4, 0xdb, 0xdd, 0xf9, 0xb6, 0xec, 0x05, 0x6e, 0xeb, 0x20, 0x13, 0x9f, 0xe8, 0x6f, 0xb3, 0x37,
	0xc5, 0xf5, 0xb2, 0x69, 0xab, 0xd7, 0x55, 0xf8, 0x1e, 0x4f, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x21, 0x6a, 0x70, 0x39, 0x4d, 0x02, 0x00, 0x00,
}
